# Generated by Django 2.1 on 2018-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=512, null=True, verbose_name='Имя пользователя')),
                ('event_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Тип события')),
                ('ip', models.CharField(blank=True, max_length=512, null=True, verbose_name='IP адрес пользователя')),
                ('agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='Информация о браузере')),
                ('host', models.CharField(blank=True, max_length=512, null=True, verbose_name='Имя хоста')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Осуществяемый переход')),
                ('accept_language', models.CharField(blank=True, max_length=512, null=True, verbose_name='Язык')),
                ('event', models.CharField(blank=True, max_length=512, null=True, verbose_name='Собыите')),
                ('event_source', models.CharField(blank=True, max_length=512, null=True, verbose_name='Server')),
                ('time', models.CharField(blank=True, max_length=512, null=True, verbose_name='Время события')),
                ('page', models.CharField(blank=True, max_length=512, null=True, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Трэкинг',
                'verbose_name_plural': 'Трэкинг',
            },
        ),
        migrations.CreateModel(
            name='TrackCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ИД пользователя')),
                ('org_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ИД организации')),
                ('course_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ИД курса')),
                ('path', models.TextField(blank=True, null=True, verbose_name='Путь перехода')),
            ],
            options={
                'verbose_name': 'Трэкинг в курсе',
                'verbose_name_plural': 'Трэкинг в курсе',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='context',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.TrackCourse', verbose_name='Контекст курса'),
        ),
    ]
